# spring
spring:
  #  aop:
  #    proxy-target-class: false
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/spring_proxyy?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
  jpa:
    properties:
      hibernate:
       show_sql: true
       format_sql: false